### ISSUE TITLE
Update the Rubric on Canvas

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/intro-to-git#100]
The current rubric doesn't reflect the changes to use pull requests and protected branches. That really should be fixed.

**Comment by kklamberty** [comment]
I've updated the rubric a bit. I'm note totally sure this encompasses all of what you wanted, but it's a start.

**Comment by NicMcPhee** [comment]
I had no real sense of what I "wanted", more a clear sense that what we were doing didn't match up with the rubric anymore.

I think there are issues with several of the other rubrics now that we have branch protection and require reviews. You and I might want to meet and talk about that.
