### ISSUE TITLE
Add Travis-CI

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/intro-to-git#12]
Now that we have a (simple) program, we could add Travis-CI so students could see the automatic builds.

We'd have to set up some sort of build system, and preferably some basic tests, but at a minimum it would verify that the program compiles and runs.

**Comment by floogulinc** [comment]
Since Gradle is the build system in future labs, we could easily use that here. We would also get testing easily from using a basic Gradle setup.

**Comment by kklamberty** [comment]
We will have to always update the Travis-CI badge in GitHub on the semester version of the repository. We should not close this issue because it will come up each semester.

**Comment by NicMcPhee** [comment]
I think that bac90b1 essentially fixes the need to leave this open forever. There's now a static "broken" badge at the top of the README with instructions on what to do after you "fork" into GitHub Classroom. Hopefully that will accomplish the task without us needed to leave an issue open indefinitely.
