### ISSUE TITLE
Update git learning goal on canvas to say something about size of commits

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/intro-to-git#14]
This semester's learning goal _only_ talks about commit messages, but we also want them to generate small, focused commits, and that should be reflected in the learning outcome and thus on the rubric.

**Comment by NicMcPhee** [comment]
Do we want two separate goals here, one for the commit messages and one for the size and focus of the commits? Or does that just overly complicate things and we just want to add the size/focus thing to existing rubric?

**Comment by NicMcPhee** [comment]
@kklamberty and I updated the commit messages rubric so includes some language about having commits be appropriately sized and focused.
