### ISSUE TITLE
Upgrade to Gradle v5

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/intro-to-git#29]
The current version of Gradle is 5.0.0 and we're using 3.1 in the labs.

I have no idea how easy/hard this will be and how it might affect things. At a minimum, I suspect it will make on-line documentation more useful. I tried changing `testCompile` to `testImplementation` to match [this quick start guide](https://guides.gradle.org/building-java-applications/) and it didn't work, presumably because our Gradle is so old.

**Comment by floogulinc** [comment]
The Gradle in the labs shouldn't matter since Gradle comes packaged in the wrapper so when you run ./gradle it's using whatever version is included. Also you can have IDEA use the wrapper instead of native (and that is probably the default functionality).

**Comment by floogulinc** [comment]
You should be able to just upgrade the Gradle wrapper in this project for now.

**Comment by NicMcPhee** [comment]
Good catch. I'd forgotten that you can even update a Gradle wrapper in place. It's a strange world we live in.

**Comment by floogulinc** [comment]
Actually, I don't see Gradle in our puppet repo for the lab so I'm not sure it is even installed locally for all users.
