### ISSUE TITLE
We may want them to install the Gradle Tasks plugin for VSCode

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/intro-to-git#39]
The Gradle Tasks plugin for VSCode adds a "Gradle Tasks" panel which allows users to run gradle tasks from VSCode in a manner similar to how that worked in IntelliJ. I don't know if it's _necessary_, but it might be useful. If we do this, we might want to create a "folder" of tasks and put "run" and "test" there so students won't have to go hunting for those in the big pile of things that gradle knows how to do.

**Comment by floogulinc** [comment]
I have tried various ways of getting automatic Gradle stuff working in VS Code and that plugin seems to work OK but it has trouble later on when we have subfolders with Gradle configs. I would suggest the easiest and most stable thing to do would be to manually make the VS Code tasks we need for running stuff with Gradle.

Alternatively, the Task Explorer plugin itself seems to pick up Gradle tasks, but only if they are manually defined. It does not pick up the automatically created ones from plugins like the `run` and `test` tasks so if we wanted to use that function we would have to make our own aliases of those tasks.

**Comment by NicMcPhee** [comment]
Hmph – it's a bummer that there isn't a clearer approach. Maybe we just skip all this and have them type `./gradlew test`?

The Task Explorer solution might be OK, but then we're wiring in very VS Code specific stuff, which will be a pain when we inevitably switch to a different setup.

**Comment by floogulinc** [comment]
I have done some experimenting and because of the customization provided by custom tasks I think that is what we will use in future labs to launch the server/client and do other things.

A basic `.vscode/tasks.json` for this project looks like this:
```json
{
    "version": "2.0.0",
    "command": "./gradlew",
    "type": "shell",
    "tasks": [
      {
        "label": "Run Program",
        "args": [
          "run"
        ]
      },
      {
        "label": "Test Program",
        "args": [
          "test"
        ],
        "group": {
          "kind": "test",
          "isDefault": true
        }
      }
    ]
}
```

And with the [Task Explorer extension](https://marketplace.visualstudio.com/items?itemName=spmeesseman.vscode-taskexplorer), it looks like this in the sidebar:

![image](https://user-images.githubusercontent.com/1300395/72712622-087bf880-3b31-11ea-93be-8d288b30e9bf.png)

**Comment by NicMcPhee** [comment]
I like how the VS Code task stuff looks, but that's all strongly tied to VS Code. I'd rather we manage tasks in something non-IDE like Gradle and have the IDE deal with them.

If we embed all that info in VS Code stuff, it potentially makes switching to a different IDEA a lot more complicated.

**Comment by NicMcPhee** [comment]
We went with the Gradle extensions for now, and we'll unwind that decision later if/as necessary.
