### ISSUE TITLE
I couldn't push a change to `.github/workflows/gradle.yaml` from GitKraken

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/intro-to-git#40]
I changed the JDK version in `.github/workflows/gradle.yaml` (which specifies the info for GitHub Actions) and GitKraken "failed" when I tried to push. The message fades away fairly quickly, but here is what I think is the core info:

> Refusing to allow an OAuth App to create or update workflow without `workflow` scope.

My guess (but it's only a guess) is that the problem is that @floogulinc used the Java CI template but then included _gradle_ actions. There is a [Gradle Command template for GitHub Actions](https://github.com/marketplace/actions/gradle-command) and I have a feeling that this is what we're _supposed_ to be using?

I tried doing the push from the command line, and it pushed fine, so it's clearly GitKraken being "smart" about something here. The action also succeeded fine, so whatever the problem is it's a "this is how you _should_ do things" as opposed to "this is how you _must_ do things" kind of issue.

**Comment by floogulinc** [comment]
This is an issue I have too. It is because GitKraken is an OAuth App on GitHub and that's how it authenticates the stuff it does. GitHub has restrictions in place to prevent such applications from modifying GitHub Actions. I have just tested and I seem to be able to push changes to a GH Action again. So it may be the case that you need to "refresh" your OAuth token for GitKraken so it gets the new permission scope. Though I do not exactly know how you might do so.

This reminds me to remind you that when you create the org for this semester to enable GitKraken for it or students won't be able to use GitKraken for repos in it.

**Comment by NicMcPhee** [comment]
> This is an issue I have too.

That sort of sucks. So we have no idea whether students will run into this or not? It won't be an issue at the beginning of the lab because the actions will all be set up by us, but it might be something they run into later in the semester.

> This reminds me to remind you that when you create the org for this semester to enable GitKraken for it or students won't be able to use GitKraken for repos in it.

Good catch. I'll create that org right now. Are there other things that will need to be enabled?

**Comment by NicMcPhee** [comment]
I've enabled access for:

- GitHub Classroom
- ZenHub
- GitKraken
- GitKraken Glo (don't know if we'll use it, but I figured I'd enable it just in case)

I didn't enable Travis since I don't think we'll be using it, but it would be easy enough to add it later if we decided that would make sense.

**Comment by NicMcPhee** [comment]
Any thoughts on whether we should be using the Gradle Command template instead of the Java Template for GitHub Actions? It seems odd to _not_ being using the Gradle tools if they exist.

**Comment by floogulinc** [comment]
The Gradle action you linked to is a third-party action while the Java template I used is exactly what GitHub suggests when you tell it you want to do Gradle (including the JDK 1.8). I didn't edit anything from what GitHub gave me. It comes from [actions/starter-workflows](https://github.com/actions/starter-workflows).


![image](https://user-images.githubusercontent.com/1300395/72689028-9d033e00-3ad2-11ea-8d87-1e25959b615b.png)

It should be noted that there is a difference between a *template* and an *action*. The thing you linked is an action that is added to a workflow. A template is what GitHub lets you choose when you create a workflow to start from.

**Comment by NicMcPhee** [comment]
Gotcha. Then I'm fine with leaving things alone, especially for now.

I'm going to leave this issue open for now just in case we find that students can't push when we do the lab. After we're done running the lab, though, then we should probably close it (assuming nothing comes up).

**Comment by NicMcPhee** [comment]
@floogulinc's comment about OAuth up above seems to be the key issue, and I don't expect that will be a problem for this lab.  In fact I doubt students will need to fiddle with the GitHub Actions config until they're into the project, if even then. So I'm going to close this.
