### ISSUE TITLE
fix any place that says the repo will be private to say nothing or public

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/intro-to-git#8]
This repo doesn't need to be private. If we're not making it private, we should be consistent about how we talk about it.

**Comment by floogulinc** [comment]
This includes on the Canvas assignment as well.

**Comment by NicMcPhee** [comment]
I'm not sure I understand what we're talking about here. The write-up only uses the word "private" once, and that's just to indicate that when you clone a copy it's a "private" copy in your home directory. Is the concern that the word "private" here is talking about repositories on Github being either public or private? We're not doing anything with private repos in this course, so we definitely want to make sure we don't confuse people about that.

**Comment by kklamberty** [comment]
We updated the Canvas description. The Github part of the world seems to have been fixed already.
